### ISSUE TITLE
Está retornando invalido para siglas iniciadas em FJ

### ISSUE THREAD

**Issue by pereira49** [gabrielboliveira/tracking-correios#1]
Estas encomendas são do DETRAN (não encontrei no site dos correios referencia a esta sigla, mas pesquisei com varias pessoas e em todas o rastreamento do detran deles de 2017 está com FJ) , fiz em meu codigo a adição do FJ na lista de validInitials. Sugiro que adicione ela também no projeto.

**Comment by gabrielboliveira** [comment]
@pereira49 obrigado! tem algum código válido com essas iniciais para eu fazer alguns testes?

**Comment by pereira49** [comment]
FJ756749108BR

**Comment by gabrielboliveira** [comment]
Corrigido na versão 1.0.8
