### ISSUE TITLE
Código de rastreio retornando Não Existente

### ISSUE THREAD

**Issue by alefcarlos** [gabrielboliveira/tracking-correios#10]
Beleza ? Primeiro, parabéns pelo pacote :-)

Estou tentando rastrear o código OF019481896 e me retorna que não existe na base dos correios.

Porém consultando via web, retorna o tracking correto.

**Comment by alefcarlos** [comment]
Desculpa, retorna erro de validação do objeto*

**Comment by gabrielboliveira** [comment]
> Beleza ? Primeiro, parabéns pelo pacote :-)

Obrigado! 😄 

> Estou tentando rastrear o código OF019481896 e me retorna que não existe na base dos correios.

Utilizei o código que vc mencionou no site do correios, e me retornou erro:
![msg de erro](https://user-images.githubusercontent.com/11093090/35150730-a48c10e4-fd02-11e7-8b3e-b8ea820036d6.png)


O código OF019481896 é inválido, não está no formato utilizado pelos Correios. Acredito que possa ter sido erro de digitação, adicionei o BR no final. Com o BR é possível procurar utilizando o tracking-correios com a flag `filter: false`, pois essa inicial não está cadastrada na lista de iniciais válidas: 
https://github.com/gabrielboliveira/tracking-correios/blob/51b72ba3d401a719862e582132d91e95c6cced91/src/utils/tracking-helpers.js#L3-L242

Utilizando a flag mencionada, a API retorna resultado:
![exemplo](https://user-images.githubusercontent.com/11093090/35150640-4904c22a-fd02-11e7-971e-69d9f2200f88.png)

Exemplo de código utilizado:

```js
const TrackingCorreios = require('tracking-correios');

TrackingCorreios.track('OF019481896BR', { filter: false })
    .then(success => {
        console.log('sucesso', success)
    }, error => {
        console.error('then.error', error)
    })
```

**Comment by alefcarlos** [comment]
Opa, beleza ? Copiei o código pelo celular e nem percebi que tava faltando o BR no final: OF019481896BR

Então nesse caso é um erro de geração de código de rastreio ?

**Comment by gabrielboliveira** [comment]
Não, o código está correto com o BR no final. O problema é que o Correios adicionou várias novas iniciais que ainda não foram mapeadas no código. 

Até o momento não consegui procurar todas as novas iniciais, então adicionei a flag `filter` para quem quiser utilizar a API sem filtrar os válidos.

Algumas pessoas criaram Pull Requests adicionando novas iniciais (#4, #7, #8, #9). Se vc quiser, pode criar um PR adicionando essa inicial 😃

**Comment by gabrielboliveira** [comment]
Obrigado pelo PR. Publicado na versão 1.1.6
