### ISSUE TITLE
[Dúvida] Histórico de Eventos

### ISSUE THREAD

**Issue by tommelo** [gabrielboliveira/tracking-correios#12]
@gabrielboliveira estou testando um código de rastreio e surgiu uma dúvida em relação ao histórico de eventos.

```js
TrackingCorreios.track('DY755678612BR')
  .then(

    (results) => {
      console.log(JSON.stringify(results, null, 2));                
    }

  ).catch(

    (error) => {
      console.error(error);                
    }

  );
```

Nesse caso, era pra api retornar o todos os eventos do objeto?
Apenas o último evento é retornado:

```
[
  {
    "numero": "DY755678612BR",
    "sigla": "DY",
    "nome": "ENCOMENDA SEDEX (ETIQ FÍSICA)",
    "categoria": "SEDEX",
    "evento": [
      {
        "tipo": "BDE",
        "status": "01",
        "data": "24/01/2018",
        "hora": "19:16",
        "descricao": "Objeto entregue ao destinatário",
        "local": "CEE SANTO AMARO",
        "codigo": "04754970",
        "cidade": "SAO PAULO",
        "uf": "SP"
      }
    ]
  }
]
```

Devo utilizar algum outro parâmetro para trazer todo o histórico?

**Comment by gabrielboliveira** [comment]
Olá @tommelo! Aparentemente, alguns meses atrás a API dos Correios mudou seu comportamento para trazer somente o último evento do objeto, quando utilizado o usuário e senha padrão. (https://github.com/pedro-teixeira/correios/issues/279#issuecomment-310200776)

Já discutimos no repositório, em outra issue (https://github.com/gabrielboliveira/tracking-correios/issues/5#issuecomment-310100798) sobre esse problema. Tentei procurar algum modo para trazer a lista completa, mas aparentemente agora só se cadastrando e gerando um usuário e senha pessoal.

Depois, só configurar quando for fazer a request:

```js
TrackingCorreios.track('DY755678612BR', {
    username: 'abc',
    password: 'abc',
});
```

**Comment by tommelo** [comment]
@gabrielboliveira ah ok! Muito obrigado!
Outro teste que fiz agora, com um tracking code válido: OF022972405BR

```
{ [TrackingError: Erro ao validar os objetos.]
  name: 'TrackingError',
  message: 'Erro ao validar os objetos.',
  type: 'validation_error',
  errors: 
   [ { message: 'Nenhum objeto válido para pesquisa.',
       service: 'objects_validation' } ] }
```

Vou tentar criar uma conta e testar novamente.
Obrigado!

**Comment by gabrielboliveira** [comment]
Se preferir não filtrar os objetos, é só passar a configuração `filter: false`: 

```js
TrackingCorreios.track('DY755678612BR', {
    filter: false,
});
```

**Comment by tommelo** [comment]
@gabrielboliveira fiz um build com a última versão, agora foi!

Conseguir as credenciais de acesso será mais difícil do que imaginei...
Partir pra alguma solução alternativa.

Podemos fechar essa issue.
Obrigado pela ajuda!

**Comment by gabrielboliveira** [comment]
Beleza! Qualquer outra dúvida só comentar na issue :)
