### ISSUE TITLE
Dúvida...

### ISSUE THREAD

**Issue by PauloBoaventura** [gabrielboliveira/tracking-correios#13]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by gabrielboliveira** [comment]
Olá Paulo, obrigado pela pergunta! 

Essa biblioteca foi feita em JavaScript para rodar em Node.js, especificamente. Eu tenho planejado o desenvolvimento da versão para PHP, porém ainda não tive tempo. 

Eu utilizo esse PDF como base para o desenvolvimento: https://m.correios.com.br/a-a-z/pdf/rastreamento-de-objetos/manual_rastreamentoobjetosws.pdf

Até o momento, o rastreio de objetos com a tracking-correios funciona perfeitamente, sem nenhum problema. Não entendo o que quer dizer com novas normativas, a API SRO não teve alterações recentes.

Sobre a questão do usuário, em [outro repositório](https://github.com/pedro-teixeira/correios/issues/279#issuecomment-310200776) relataram a necessidade de ter usuário e senha válidos para retornar o histórico de rastreio.

Existem diversas opções em PHP disponíveis, mas acredito que você já tenha encontrado. 

Relacionado:

pedro-teixeira/correios#355
guilhermechapiewski/correios-api#3
olist/correios#122
bubbstore/correios#5
bubbwebstudio/bubb-correios#1

**Comment by PauloBoaventura** [comment]
Olá, @gabrielboliveira 
Bom estou com diversos problemas e não sou o único. 
Especificamnete no Magento 1.9, sobre a extensão CORREIOS.

Agora... Sobre a [https://github.com/pedro-teixeira/correios/issues/355]
Ela não esta com qualquer atualização, suporte ou em funcionamento.
Diversas pessoas estão com o mesmo problema... 
O que é significa grande "desatualização" e sem comunicados oficiais.
Se souber algumas das referidas que esteja funcionando desde outubro de 2017, por favor mencione!
Você citou que seu planejamento é em base de desenvolvimento. O que não entrei no merito, já que temos tantas opções (que eram de qualidade), mas que hoje possuem grande defasagem, como cito anteriormente. 

Agradeço pela ajuda e atenção!

**Comment by gabrielboliveira** [comment]
Não sei te informar qual repositório está funcionando. Se quiser integrar essa biblioteca, fique a vontade, porém acredito não servir. 

Não pretendo criar um plugin para o Magento, por não utilizá-lo e nem conhecê-lo.

> Ela não esta com qualquer atualização, suporte ou em funcionamento. Diversas pessoas estão com o mesmo problema... O que é significa grande "desatualização" e sem comunicados oficiais.

Não é assim que a comunidade open-source funciona. Sem dúvida é ótimo para a comunidade os repositórios atualizados e mantidos. Porém, uma pessoa que criou um projeto não tem necessariamente responsabilidade sobre ele, para atualizá-lo ou até mantê-lo. Algumas vezes as pessoas compartilham os seus projetos pessoais com a comunidade, as vezes até sem intenção de atualizá-la. 

Como pode perceber, o criador desse módulo não tem nenhuma atividade recente no Github, e não atualiza essa biblioteca desde 27 de agosto de 2017. 

Qualquer um é livre para criar um fork do repositório e atualizá-lo com as novas normativas do Correios. 

Se você não conseguir atualizá-la, recomendo entrar em contato com alguma empresa de desenvolvimento de software que possa te ajudar, existem várias bem qualificadas no Brasil.
