### ISSUE TITLE
A API retorna somente o evento da postagem, enquanto o rastreamento dos correios retorna outros 10 eventos

### ISSUE THREAD

**Issue by klawdyo** [gabrielboliveira/tracking-correios#16]
Os objetos pesquisados são os DY277947771BR e DY101423198BR

**Comment by klawdyo** [comment]
Resultado da API
![image](https://user-images.githubusercontent.com/100168/44061926-b2f15b32-9f30-11e8-9714-5221edcab749.png)
Resultado no site dos correios
![image](https://user-images.githubusercontent.com/100168/44061944-cfcfa9c0-9f30-11e8-8816-e7750676b2c3.png)

**Comment by gabrielboliveira** [comment]
Opa @klawdyo, obrigado pela issue!

A API utiliza por padrão o usuário ECT, e conforme informado pelos Correios para mim por email, esse é somente um usuário de testes, retornando poucas informações. https://github.com/gabrielboliveira/tracking-correios/issues/15#issuecomment-407868294

Coloquei no [README](https://github.com/gabrielboliveira/tracking-correios/blob/master/README.md#atenÇÃo) pra ficar mais claro.

Infelizmente nada que possamos fazer em relação a isso. Cada usuário deve se cadastrar e pedir seu próprio usuário aos Correios.

**Comment by klawdyo** [comment]
Hum. Entendi. Só uma dúvida básica: Esse cadastro com os Correios é pago?

**Comment by gabrielboliveira** [comment]
Não sei te informar. Envia um email pra eles: sro@correios.com.br

Aqui a informação sobre usuário e senha: http://www.correios.com.br/solucoes-empresariais/comercio-eletronico/sistema-de-rastreamento-de-objetos
