### ISSUE TITLE
Unhandled rejection TrackingError: Erro no serviço do Correios.

### ISSUE THREAD

**Issue by flourigh** [gabrielboliveira/tracking-correios#17]
Está dando este erro no console

**Comment by gabrielboliveira** [comment]
Poderia ser mais específico, com explicação em que método está dando problema, exemplo de teste, código de rastreio que está quebrando.

**Comment by flourigh** [comment]
@gabrielboliveira na verdade eu só coloco o código do rastreio JTBR e este erro aparece, não é exatamente auto explicativo, não sei como dar mais explicação de verdade

**Comment by gabrielboliveira** [comment]
Qual código de rastreio específico está dando problema? Vc pode tentar rastrear melhor o erro usando try/catch ou então .catch

**Comment by gabrielboliveira** [comment]
Veja alguns exemplos de issues que consegui ajudar as pessoas: #10 #12 #15. Sem um exemplo de como vc está tentando usar, fica complicado entender o erro.
