### ISSUE TITLE
Objetos invalidos

### ISSUE THREAD

**Issue by ThalesMatoso** [gabrielboliveira/tracking-correios#19]
Estou utlizando 3 codigos de rastreamento nos quais me retornam somente que está invalidos, mas ao pesquisar no site da correios me retorna normalmente o rastro

sabe me dizer o que pode ser?

segue os 3 objetos junto ao código

`const objects = TrackingCorreios.validate(['PS707468874BR', 'PS707765532BR', 'PS707901927BR']);`
`console.log(objects);`
`{ valid: [], invalid: [ 'PS707468874BR', 'PS707765532BR', 'PS707901927BR' ] }`

**Comment by gabrielboliveira** [comment]
A inicial PS ainda não foi mapeada como válida. Recentemente o Correios decidiu mudar as siglas utilizadas, eu fiz um novo mapeamento recentemente usando o [site do próprio Correios](https://www.correios.com.br/precisa-de-ajuda/como-rastrear-um-objeto/siglas-utilizadas-no-rastreamento-de-objeto).

Na época o código PS ainda não existia. Se quiser adicionar, existem alguns exemplos de pessoas que abriram PR adicionando. Veja #10 para entender melhor.

Se não conseguir, assim que eu tiver um tempo eu adiciono o código novo, porém sem previsão 😄 

Pretendo em breve adicionar mais opções para o pacote, como desabilitar a validação de categoria, mantendo somente o padrão AA000000000BR. Atualmente somente o método `track` tem a opção de não validar nada (`filter: false`).

**Comment by gabrielboliveira** [comment]
Iniciais adicionadas na versão 1.1.8.
