### ISSUE TITLE
Nova sigla retornando inválido DY

### ISSUE THREAD

**Issue by pereira49** [gabrielboliveira/tracking-correios#3]
Gabriel, seria interessante, aceitar alguma configuração opcional para ele não validar na lista de siglas, se for o desejo do usuário, o que acha dessa feature? Dessa forma, o usuário que desejar validar, poderia continuar usando sua validação, ou apenas realizar a consulta diretamente nos correios e se for inválido teriamos a exception.

Segue um exemplo retornando erro: DY158408516BR.

**Comment by gabrielboliveira** [comment]
Obrigado pelo feedback! Gostei da ideia. Assim que possível adiciono essa nova sigla e também a opção para ignorar validação

**Comment by gabrielboliveira** [comment]
Corrigido na versão 1.1.0. Adicionei também a opção de eliminar os filtros:

```js
TrackingCorreios.track( 'invalido', { filter: false } )
```
