### ISSUE TITLE
Retorno do método  tracking error undefined

### ISSUE THREAD

**Issue by Victormatheus819** [gabrielboliveira/tracking-correios#31]
quando estou passando um código de rastreio   :  Ele retorna "O serviço do Correios retornou o seguinte erro: undefined".

**Comment by gabrielboliveira** [comment]
Pode me passar mais informações, sobre como está usando o método e um código para eu poder testar?

**Comment by Victormatheus819** [comment]
Eu estou usando primeiramente para fazer um teste pra ver se retorna alguma coisa, onde mostro um botão e deveria retornar no console a resposta, estou usando o **vue.cli,** estou usando como teste um código de rastreio meu que o produto já foi entregue.
O código está assim:

![Capturar](https://user-images.githubusercontent.com/42408625/69065377-08a72d00-09f6-11ea-83e8-0828a8ea1f06.PNG)

**Comment by gabrielboliveira** [comment]
A API do Correios não permite CORS ([se quiser saber mais](https://medium.com/@alexandremjacques/entendendo-o-cors-parte-8331d0a777e1)). Para fazer a requisição pelo Vue, vc precisa de uma API própria como proxy para fazer a requisição no backend, e não no navegador.

Veja a mesma requisição feita usando o node:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/11093090/69066784-3dc97480-0a22-11ea-9f22-4ad3cb5565c0.png">

Eu implementei a um tempo atrás essa API, porém está desatualizada: https://github.com/gabrielboliveira/rest-tracking

**Comment by gabrielboliveira** [comment]
Fechando o ticket por inatividade.
