### ISSUE TITLE
Inclusão de usuário e senha de contrato

### ISSUE THREAD

**Issue by Juuhz** [gabrielboliveira/tracking-correios#33]
Tenho uma dúvida:

Eu tenho contrato com os correios, porém, não há suporte para configuração dos mesmo, como posso estar realizando essa configuração?

Abraços.

**Comment by gabrielboliveira** [comment]
Você pode enviar usuário e senha no segundo parâmetro do método `track`:

```js
TrackingCorreios.track('codigo', {
    username: "seu-usuario",
    password: "sua-senha",
});
```

**Comment by gabrielboliveira** [comment]
@Juuhz Conseguiu? Posso fechar o ticket?

**Comment by gabrielboliveira** [comment]
Fechando por inatividade. Se precisar de ajuda, fique a vontade em reabrir o ticket ou abrir uma nova issue.

**Comment by vitordhers** [comment]
Surgiu uma dúvida, esses dados são o usuário e senha do correios fácil ou do sigep?

obs.: Obrigado por ter desenvolvido essa solução.

Att,
