### ISSUE TITLE
Recebendo apenas um evento.

### ISSUE THREAD

**Issue by venanciosouza** [gabrielboliveira/tracking-correios#34]
Olá! Parabéns pelo trabalho! Gostaria de saber se é normal receber apenas um evento, pois já tentei com dois códigos de rastreio que tem mais de um evento e sempre o pacote me retorna apenas um(evento: [{}]) um array com uma posição apenas. De já, muito obrigado.

**Comment by gabrielboliveira** [comment]
Olá @venanciosouza! Obrigado 😄 

[Conforme descrito no README](https://github.com/gabrielboliveira/tracking-correios#aten%C3%A7%C3%A3o), o usuário padrão ECT é somente um usuário de testes, limitado a um evento somente. Para aumentar isso é necessário obter um usuário e senha válidos diretamente com eles.

**Comment by venanciosouza** [comment]
@gabrielboliveira nossa.. nunca imaginei isso kkk Muito obrigado!!

**Comment by gabrielboliveira** [comment]
Quando eu fiz esse projeto, em 2017, não precisava. Colocaram essa limitação a um tempo 😄

**Comment by venanciosouza** [comment]
@gabrielboliveira ficou muito bom. Tô usando em um app de rastreio que tô faz endo em RN... Vou criar uma conta lá.. espero que seja free kkk
