### ISSUE TITLE
A descrição sempre retorna  <descricao>Objeto postado</descricao> 

### ISSUE THREAD

**Issue by faraddouglas** [gabrielboliveira/tracking-correios#37]
Olá boa noite, sabe o que pode estar acontecendo com o webservice? O retorno da api sepmpre é "Objeto postado" mesmo que o objeto já esteja entregue.

**Comment by gabrielboliveira** [comment]
@faraddouglas Qual código de rastreio por favor?

**Comment by SirKrilhos** [comment]
Olá boa noite, comigo também está acontecendo isso.
O meu código é "PW541511679BR", eu li em outras issues que tem a ver com a api dos correios retornar apenas 1 evento pelo tipo de conta utilizada, isso ainda procede? 

<img width="361" alt="Captura de Tela 2020-06-07 às 9 44 44 PM" src="https://user-images.githubusercontent.com/17271215/83983863-22637f80-a908-11ea-8650-f0431eb87c93.png">

**Comment by gabrielboliveira** [comment]
O `tracking-correios` foi desenvolvido com intuito de fazer uma ponte direta com a API SOAP do Correios. O problema citado acima por @SirKrilhos é real, eles limitaram o acesso do usuário padrão ECT para somente um evento, por ser um usuário de testes da aplicação. Isso está descrito no README: https://github.com/gabrielboliveira/tracking-correios#atenção

Para trazer todos os códigos de rastreio, e poder enviar até 5 mil códigos de uma só vez, é necessário obter um usuário e senha com eles.

No futuro pretendo mudar esse pacote para acessar mais de um serviço ao mesmo tempo, tanto dos Correios (API oficial e não-oficial), quanto outros serviços. Atualmente está limitado a esse problema do usuário/senha.

**Comment by faraddouglas** [comment]
Opa, é isto mesmo entrei em contato com os correios. Para este usuário de teste "ECT" somente retorna o primeiro evento. Muito obrigado a todos.
