### ISSUE TITLE
Some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by klaveren** [gabrielboliveira/tracking-correios#40]
Hi Devs,

In a few days ago the npm audit security report identify a security problem Denial of Service in the node-fetch.
The notify is here https://npmjs.com/advisories/1556. And the solution is update the node-fetch to version => 3.0

You have some idea to update the package in the near future?

Thanks

**Comment by gabrielboliveira** [comment]
Updated on version 1.2.3, already published. Thanks for your report

**Comment by klaveren** [comment]
Obrigado Gabriel. Parabéns pelo projeto.

**Comment by gabrielboliveira** [comment]
@klaveren Eu uso o Yarn no projeto, e rodando `yarn audit` encontra somente 2 libs com vulnerabilidades "low". Depois de adicionar essas duas no `package.json` como `resolutions`, forçando essa versão, resolveu e não apareceu a node-fetch.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/11093090/95387016-8bfb9680-08c6-11eb-8271-e0464d1efaee.png">

Como vc pode ver no `package.json`, eu forcei a versão ^2.6.1 do note-fetch. Deve ser alguma configuração no seu lock file que não está carregando as dependências corretas.
https://github.com/gabrielboliveira/tracking-correios/blob/d8aaadf9636072f3635eafa800cdbe404518330a/package.json#L40-L44

Recomendo vc remover e adicionar novamente o pacote do `tracking-correios` na versão 1.2.3.

Já fiz uma boa refatoração de código, está no branch `dev`. Removi inclusive essa `isomorphic-fetch` que causa os problemas de vulnerabilidade. Vou realizar mais alguns testes antes de taggear.

**Comment by klaveren** [comment]
Interessante, é pena que no npm eu não consigo usar resolutions de forma nativa. 
Fiz o que você recomendou, até reinstalei todas as minhas dependências. Mas ainda sem sucesso. To te mandando um log para você ver como tá sendo apresentada a mensagem aqui pra quem usa o NPM.

Obrigado.

![Screen Shot 2020-10-08 at 12 35 57](https://user-images.githubusercontent.com/13166046/95481184-1abdf100-0963-11eb-86a1-c871545b68a6.png)

**Comment by gabrielboliveira** [comment]
@klaveren Atualizei para versão [1.3.0](https://github.com/gabrielboliveira/tracking-correios/releases/tag/v1.3.0). Pode tentar usar essa nova versão? Contém várias atualizações de pacotes internos.

**Comment by klaveren** [comment]
Que legal, muito obrigado. Está tudo funcionando perfeitamente. Parabéns pelo trabalho.
