### ISSUE TITLE
Erro ao realizar consulta

### ISSUE THREAD

**Issue by pereira49** [gabrielboliveira/tracking-correios#5]
Estou recebendo o erro ao rastrear a encomenda de exemplo e outras encomendas
exemplo: PL185055478BR
erro: Unhandled rejection TrackingError: _get(...).map is not a function

**Comment by gabrielboliveira** [comment]
Esse código está retornando `java.lang.NullPointerException` da API dos correios.

Vou atualizar o método para retornar melhor o erro ao usuário.

**Comment by gabrielboliveira** [comment]
@pereira49 versão 1.1.1 publicada, com o erro corrigido.

A Promise será rejeitada com o erro mais bonito:

```js
TrackingCorreios.track( 'PL185055478BR' )
    .then(sucesso => {
        console.log(sucesso)
    }, error => {
       console.error(error)
    })
```
```
{ [TrackingError: Erro no serviço do Correios.]
  name: 'TrackingError',
  message: 'Erro no serviço do Correios.',
  type: 'service_error',
  errors:
   [ { message: 'O serviço do Correios retornou o seguinte erro: java.lang.NullPointerException',
       service: 'service_error' } ] }
```

Você pode validar se o erro for uma instância de TrackingError e verificar se o `type` é `service_error`.

Por algum motivo a API do Correios está retornando `java.lang.NullPointerException` o dia todo hoje, nada muito que eu possa fazer 😄

**Comment by ronaldocuca** [comment]
Aqui voltou a funcionar setando as variáveis: username: "ECT", password: "SRO"

**Comment by gabrielboliveira** [comment]
@ronaldocuca obrigado! Vou confirmar na documentação dos correios, mas provavelmente não estão mais aceitando usuário e senha em branco.

Vou colocar esses dados que me passou como padrão do pacote.

**Comment by ronaldocuca** [comment]
@gabrielboliveira Percebe que só está retornando o último status do objeto. Têm alguma ideia do que pode ser?

**Comment by gabrielboliveira** [comment]
@ronaldocuca Testando pelo SoapUI, vi que a API do Correios está retornando um único evento por pacote, no caso o último, independente da chamada utilizada (`buscaEventos` ou `buscaEventosLista`). Pode ser uma mudança no comportamento da API deles ou então algum dos parâmetros (tipo, resultado ou lingua) pode ter sido alterado. 

O único documento que eu tenho é [este](https://www.correios.com.br/para-voce/correios-de-a-a-z/pdf/rastreamento-de-objetos/manual_rastreamentoobjetosws.pdf), que não diz nada sobre alteração.

Os campos são listados no item 10, porém mesmo utilizando os padrões ali especificados, somente um evento está sendo retornado.

**Comment by gabrielboliveira** [comment]
@ronaldocuca adicionei o usuário e senha padrão que me informou no pacote, disponibilizado na versão 1.1.2. Obrigado!
