### ISSUE TITLE
API retornando apenas primeiro evento

### ISSUE THREAD

**Issue by achambel** [gabrielboliveira/tracking-correios#61]
Ola, obrigado por partilhar esta lib. 
Por alguma razao API SOAP esta retornando apenas dados do primeiro evento. Entendo que o problema esta no lado dos Correios e foge do escopo desse projeto, mas se descobrirem outro endpoint que liste todos eventos seria de grande valia.

Obrigado!

**Comment by gabrielboliveira** [comment]
Conforme informado no [README](https://github.com/gabrielboliveira/tracking-correios#aten%C3%A7%C3%A3o):

> O usuário padrão do sistema é `ECT`. Esse é um usuário de testes, por isso tem algumas limitações ([#15](https://github.com/gabrielboliveira/tracking-correios/issues/15), [#5](https://github.com/gabrielboliveira/tracking-correios/issues/5)). Só é possível fazer a consulta de 1 código por vez, e também só 1 evento é retornado. Para adquirir um usuário com mais permissões, é necessário ter um contrato com os Correios: http://www.correios.com.br/solucoes-empresariais/comercio-eletronico/sistema-de-rastreamento-de-objetos.

Esse pacote foi desenvolvido para uso direto com a API do Correios, SRO. Existem outras disponíveis que se utilizam de outros meios / endpoints que retornam todos os eventos.
